// Verdant site — generated by Panda. The scripts in this folder are the only
// "source" Panda extracts from (see panda.config.ts `include`): every
// css()/pattern()/recipe() call is a literal call, so `panda cssgen` can
// statically find it and emit exactly the CSS the pages use, nothing more.
import { writeFileSync, mkdirSync, readFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { css } from '../styled-system/css/index.mjs'
import { flex, vstack, hstack } from '../styled-system/patterns/index.mjs'
import { button, card, fieldInput, switchTrack, spinner, skeleton } from '../styled-system/recipes/index.mjs'
import { heroArt, mark, stageGlyph, leafRow, seedlingArt } from './art.mjs'
import {
  themeOverrideAttr,
  themePreferenceAttr,
  themePreferenceControlName,
  themePreferenceStorageKey,
  themePreferenceValues,
  themeResolvedAttr,
  themeTokenCount,
  themeTokens,
} from './theme.mjs'
import { paletteSections, verifiedPairings, publicTokenScope } from './tokens.mjs'

// A hand-rolled recursive copy: some mounted/virtual filesystems choke on
// Node's native cpSync fast paths (fcopyfile/clonefile), so this sticks to
// plain read/write, which works everywhere.
function copyDir(src, dest) {
  mkdirSync(dest, { recursive: true })
  for (const entry of readdirSync(src)) {
    const srcPath = join(src, entry)
    const destPath = join(dest, entry)
    if (statSync(srcPath).isDirectory()) copyDir(srcPath, destPath)
    else writeFileSync(destPath, readFileSync(srcPath))
  }
}

const REPO = 'https://github.com/ivanoats/verdant-wsg-demo'
const WSG_CHECK = 'https://github.com/ivanoats/wsg-check'
const WSG = 'https://w3c.github.io/sustainableweb-wsg/'
const COMPONENTS_ROUTE = '/components'
const COMPONENTS_FILE = '/components.html'
const evidenceRecord = JSON.parse(readFileSync('public/wsg-evidence.json', 'utf8'))

// ---- shell ------------------------------------------------------------------

const skipLinkCss = css({
  position: 'absolute', left: '3', top: '-48px',
  background: 'surface.200', color: 'ink', paddingBlock: '2', paddingInline: '4',
  borderRadius: 'sm', border: '1px solid', borderColor: 'border.control', zIndex: '10', textDecoration: 'none',
  _motionSafe: { transition: 'top 120ms ease' },
  _focus: { top: '3' },
})
const wrapCss = css({ maxWidth: '1080px', marginX: 'auto', paddingInline: { base: '4', md: '6' } })
const headerCss = css({ borderBottom: '1px solid', borderColor: 'border' })
const barCss = flex({ paddingBlock: '3', align: 'center', justify: 'space-between', gap: '4', wrap: 'wrap' })
const wordmarkCss = hstack({ gap: '2', color: 'ink', textDecoration: 'none', fontSize: 'displaySm', lineHeight: 'displaySm', fontWeight: '700' })
const headerActionsCss = flex({ align: 'center', gap: '4', wrap: 'wrap' })
const navListCss = hstack({ gap: { base: '3', md: '6' }, listStyle: 'none', margin: '0', padding: '0' })
const navLinkCss = css({ textDecoration: 'none', fontSize: 'bodySm', fontWeight: '600', color: 'ink', _hover: { color: 'accent' } })
const navLinkActiveCss = css({ textDecoration: 'underline', textUnderlineOffset: '6px', textDecorationThickness: '2px', fontSize: 'bodySm', fontWeight: '600', color: 'accent' })
const themePrefCss = css({
  display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: '8px',
  border: '0', margin: '0', padding: '0',
})
const themePrefLegendCss = css({ fontSize: 'label', lineHeight: 'label', fontWeight: '600', color: 'ink.muted', margin: '0', padding: '0' })
const themePrefOptionCss = css({
  display: 'inline-flex', alignItems: 'center', gap: '2',
  paddingBlock: '1', paddingInline: '3', border: '1px solid', borderColor: 'border',
  borderRadius: 'full', background: 'surface.200', fontSize: 'label', lineHeight: 'label', fontWeight: '600',
})
const themePrefRadioCss = css({ margin: '0', accentColor: 'accent' })

const breadcrumbListCss = hstack({ gap: '1', listStyle: 'none', margin: '0', paddingTop: '3', paddingInline: '0', fontSize: 'label', color: 'ink.muted' })
const breadcrumbLinkCss = css({ color: 'ink.muted', textDecoration: 'none' })

const footerCss = css({ borderTop: '1px solid', borderColor: 'border' })
const footerBarCss = flex({ paddingBlock: '6', align: 'center', justify: 'space-between', gap: '4', wrap: 'wrap' })
const footerBrandCss = hstack({ gap: '2' })
const footerTextCss = css({ color: 'ink.muted', fontSize: 'label', lineHeight: 'label', margin: '0' })
const footerLinksCss = hstack({ gap: '4', listStyle: 'none', margin: '0', padding: '0', fontSize: 'label' })

// ---- shared type & blocks ------------------------------------------------------

const sectionCss = css({ paddingBlock: { base: '12', md: '16' } })
const bandCss = css({ background: 'surface.200', borderBlock: '1px solid', borderColor: 'border' })
const eyebrowCss = css({ fontSize: 'label', lineHeight: 'label', fontWeight: '600', letterSpacing: '0.02em', color: 'accent', margin: '0 0 12px' })
const h2Css = css({ fontSize: { base: 'displayMd', md: 'displayLg' }, lineHeight: { base: 'displayMd', md: 'displayLg' }, fontWeight: '700', margin: '0 0 12px', maxWidth: '24ch' })
const introCss = css({ color: 'ink.muted', margin: '0 0 32px', maxWidth: '62ch' })
const codeCss = css({ fontFamily: 'mono', fontSize: 'label' })
const btnPrimary = button({ variant: 'primary' })
const btnSecondary = button({ variant: 'secondary' })
const btnRowCss = flex({ gap: '3', wrap: 'wrap', marginTop: '6' })

// ---- index: hero ------------------------------------------------------------------

const heroCss = css({
  display: 'grid', gap: { base: '6', md: '8' }, alignItems: 'center',
  gridTemplateColumns: { base: '1fr', md: '1fr 1fr' },
  paddingTop: { base: '8', md: '12' }, paddingBottom: { base: '8', md: '12' },
})
const heroTitleCss = css({ fontSize: { base: '56px', md: '88px' }, lineHeight: '0.95', fontWeight: '700', letterSpacing: '-0.02em', margin: '0' })
const heroTagCss = css({ fontSize: { base: 'displaySm', md: 'displayMd' }, lineHeight: { base: 'displaySm', md: 'displayMd' }, fontWeight: '600', color: 'accent', margin: '16px 0 0', maxWidth: '22ch' })
const heroLedeCss = css({ color: 'ink.muted', margin: '16px 0 0', maxWidth: '52ch' })
const heroArtCss = css({ '& svg': { display: 'block', width: '100%', height: 'auto', maxWidth: '560px', marginInline: 'auto' } })

const heroHtml = `
<section class="${wrapCss}" aria-labelledby="hero-title">
  <div class="${heroCss}">
    <div>
      <p class="${eyebrowCss}">A design system for the <a href="${WSG}">W3C Web Sustainability Guidelines</a></p>
      <h1 id="hero-title" class="${heroTitleCss}">Verdant</h1>
      <p class="${heroTagCss}">Sustainable Defaults for the Green Web</p>
      <p class="${heroLedeCss}">Start with the parts teams usually add later: system fonts, a System/Light/Dark theme preference, restrained motion, and only the CSS each page uses. Verdant gives a product page or docs site those lighter defaults from the first commit.</p>
      <div class="${btnRowCss}">
        <a class="${btnPrimary}" href="${COMPONENTS_ROUTE}">Browse components</a>
        <a class="${btnSecondary}" href="${REPO}">View source on GitHub</a>
      </div>
    </div>
    <div class="${heroArtCss}">${heroArt()}</div>
  </div>
</section>`

// ---- index: measured stats (filled in by scripts/stats.mjs after fingerprinting)

const statsGridCss = css({
  display: 'grid', // minmax(0, 1fr): a wide fallback font must not stretch a column past the viewport.
  gridTemplateColumns: { base: 'repeat(2, minmax(0, 1fr))', md: 'repeat(4, minmax(0, 1fr))' },
  gap: { base: '6', md: '8' }, margin: '0', paddingBlock: '8',
})
const statCss = css({ display: 'flex', flexDirection: 'column-reverse', margin: '0' })
const statValueCss = css({ fontSize: { base: 'displayMd', sm: 'displayLg', md: '40px' }, lineHeight: { base: 'displayMd', sm: 'displayLg', md: '48px' }, fontWeight: '700', color: 'accent', margin: '0' })
const statLabelCss = css({ fontSize: 'bodySm', lineHeight: 'bodySm', color: 'ink.muted', margin: '4px 0 0' })
const statsNoteCss = css({ fontSize: 'bodySm', lineHeight: 'bodySm', color: 'ink.muted', margin: '0 0 8px' })

const statsHtml = `
<section class="${bandCss}" aria-label="By the numbers">
  <div class="${wrapCss}">
    <dl class="${statsGridCss}">
      <div class="${statCss}"><dt class="${statLabelCss}">Initial render assets, local Brotli estimate</dt><dd class="${statValueCss}">__INITIAL_RENDER_KIB__&nbsp;KiB</dd></div>
      <div class="${statCss}"><dt class="${statLabelCss}">Offline shell + worker, unique local Brotli estimate</dt><dd class="${statValueCss}">__OFFLINE_SHELL_KIB__&nbsp;KiB</dd></div>
      <div class="${statCss}"><dt class="${statLabelCss}">Cold first session, measured local transfer</dt><dd class="${statValueCss}">__COLD_SESSION_KIB__&nbsp;KiB</dd></div>
      <div class="${statCss}"><dt class="${statLabelCss}">Warm repeat visit, measured local transfer</dt><dd class="${statValueCss}">__WARM_SESSION_KIB__&nbsp;KiB</dd></div>
    </dl>
    <p class="${statsNoteCss}">Measured __MEASURED_ON__ locally over HTTP with Brotli response bodies in KiB (1024 bytes), excluding headers, then rounded up to a stable tenth for this summary. Cold includes the service worker install and its duplicate precache fetches; warm is a repeat visit with the shell already cached. Production-network transfer is unmeasured here.</p>
  </div>
</section>`

// ---- index: how it grows ----------------------------------------------------------

const stagesCss = css({
  display: 'grid', gridTemplateColumns: { base: '1fr', sm: 'repeat(2, 1fr)', lg: 'repeat(4, 1fr)' },
  gap: '4', listStyle: 'none', margin: '0', padding: '0',
})
const stageCss = card()
const stageGlyphCss = css({ display: 'block', marginBottom: '3' })
const stageStepCss = css({ fontSize: 'label', lineHeight: 'label', fontWeight: '600', color: 'ink.muted', margin: '0' })
const stageTitleCss = css({ fontSize: 'displaySm', lineHeight: 'displaySm', fontWeight: '600', margin: '4px 0 8px' })
const stageBodyCss = css({ fontSize: 'bodySm', lineHeight: 'bodySm', color: 'ink.muted', margin: '0' })

const stages = [
  ['seed', 'Seed', 'Tokens', `${themeTokenCount} colors, a 4px spacing grid, four radii and system type. Small enough to stay consistent without one-off values.`],
  ['sprout', 'Sprout', 'Components', 'Button, card, field, theme preference, switch specimen and motion &mdash; each one demonstrates a WSG behavior live instead of describing it.'],
  ['sapling', 'Sapling', 'Pages', 'A product page or docs page gets landmarks, a skip link, one focus ring, one stylesheet and two small same-origin scripts from day one.'],
  ['canopy', 'Canopy', 'Sites', 'Security headers, cache rules, an offline shell and a real 404 &mdash; the hosting checks, handled before launch.'],
]
const stagesHtml = `
<section class="${wrapCss} ${sectionCss}" aria-labelledby="grows-title">
  <p class="${eyebrowCss}">How it grows</p>
  <h2 id="grows-title" class="${h2Css}">From a small token set to a whole site.</h2>
  <p class="${introCss}">Each layer only adds the parts the previous one cannot, which keeps the finished site small.</p>
  <ol class="${stagesCss}">
    ${stages.map(([key, stage, layer, body], i) => `
    <li class="${stageCss}">
      <span class="${stageGlyphCss}">${stageGlyph[key]}</span>
      <p class="${stageStepCss}">${i + 1} &middot; ${stage}</p>
      <h3 class="${stageTitleCss}">${layer}</h3>
      <p class="${stageBodyCss}">${body}</p>
    </li>`).join('')}
  </ol>
</section>`

// ---- index: palette, pairings and token scope --------------------------------------

const paletteGridCss = css({
  display: 'grid', gridTemplateColumns: { base: '1fr', lg: 'repeat(2, minmax(0, 1fr))' },
  gap: '4', listStyle: 'none', margin: '0', padding: '0',
})
const swatchCardCss = card()
const swatchNameCss = css({ fontFamily: 'mono', fontSize: 'bodySm', lineHeight: 'bodySm', fontWeight: '600', margin: '0' })
const swatchThemeGridCss = css({ display: 'grid', gridTemplateColumns: { base: '1fr', sm: 'repeat(2, minmax(0, 1fr))' }, gap: '3', marginTop: '3' })
const swatchThemeTileCss = css({
  display: 'grid', gridTemplateColumns: '48px 1fr', gap: '3', alignItems: 'center',
  border: '1px solid', borderColor: 'border', borderRadius: 'sm', padding: '3', background: 'surface.100',
})
const swatchThemeLabelCss = css({ display: 'block', fontSize: 'label', lineHeight: 'label', fontWeight: '600', margin: '0' })
const swatchHexCss = css({ display: 'block', fontFamily: 'mono', fontSize: 'label', lineHeight: 'label', color: 'ink.muted', marginTop: '4px' })
const pairingGridCss = css({ display: 'grid', gridTemplateColumns: { base: '1fr', lg: 'repeat(2, minmax(0, 1fr))' }, gap: '4', listStyle: 'none', margin: '0', padding: '0' })
const pairingCardCss = card()
const pairingTitleCss = css({ fontSize: 'displaySm', lineHeight: 'displaySm', fontWeight: '600', margin: '0' })
const pairingTokenCss = css({ fontFamily: 'mono', fontSize: 'label', lineHeight: 'label', margin: '8px 0 0' })
const pairingBodyCss = css({ fontSize: 'bodySm', lineHeight: 'bodySm', color: 'ink.muted', margin: '8px 0 0' })
const pairingMetaCss = css({ fontSize: 'label', lineHeight: 'label', color: 'ink.muted', margin: '12px 0 0' })
const scopeGridCss = css({ display: 'grid', gridTemplateColumns: { base: '1fr', lg: 'repeat(2, minmax(0, 1fr))' }, gap: '4' })
const scopeCardCss = card()
const scopeTitleCss = css({ fontSize: 'displaySm', lineHeight: 'displaySm', fontWeight: '600', margin: '0 0 8px' })
const scopeBodyCss = css({ fontSize: 'bodySm', lineHeight: 'bodySm', color: 'ink.muted', margin: '0 0 12px' })
const scopeListCss = css({ margin: '0', paddingLeft: '20px', color: 'ink.muted', '& li + li': { marginTop: '2' } })
const scopeCodeCss = css({ fontFamily: 'mono', fontSize: 'label', lineHeight: 'label', color: 'ink' })
const paletteGroupCss = css({ fontSize: 'displaySm', lineHeight: 'displaySm', fontWeight: '600', margin: '0 0 4px' })
const paletteGroupNoteCss = css({ fontSize: 'bodySm', lineHeight: 'bodySm', color: 'ink.muted', margin: '0 0 20px', maxWidth: '68ch' })
const paletteGapCss = css({ marginTop: '12' })

const hexToRgb = (hex) => [0, 2, 4].map((offset) => Number.parseInt(hex.slice(offset + 1, offset + 3), 16) / 255)
const relativeLuminance = (hex) => {
  const [r, g, b] = hexToRgb(hex).map((channel) => (channel <= 0.03928 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4))
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}
const contrast = (foreground, background) => {
  const [lighter, darker] = [relativeLuminance(foreground), relativeLuminance(background)].sort((a, b) => b - a)
  return (lighter + 0.05) / (darker + 0.05)
}
const formatRatio = (ratio) => `${ratio.toFixed(2)}:1`
const tokenCode = (token) => `<code class="${codeCss}">${token}</code>`
const leafSwatch = (fill, stroke) => `<svg viewBox="0 0 48 48" width="48" height="48" aria-hidden="true" focusable="false"><path d="M8 40V14c0-3.3 2.7-6 6-6h26v26c0 3.3-2.7 6-6 6H8Z" fill="${fill}" stroke="${stroke}" stroke-width="2"/></svg>`
const swatchTile = (themeLabel, fill, stroke) => `
        <div class="${swatchThemeTileCss}">
          ${leafSwatch(fill, stroke)}
          <span><span class="${swatchThemeLabelCss}">${themeLabel}</span><span class="${swatchHexCss}">${fill}</span></span>
        </div>`
const themeValueMaps = {
  light: Object.fromEntries(Object.entries(themeTokens).map(([key, value]) => [key, value.light])),
  dark: Object.fromEntries(Object.entries(themeTokens).map(([key, value]) => [key, value.dark])),
}

const swatches = (keys) => keys.map((key) => {
  const token = themeTokens[key]
  return `
      <li class="${swatchCardCss}">
        <p class="${swatchNameCss}">${key}</p>
        <div class="${swatchThemeGridCss}">
          ${swatchTile('Light', token.light, themeValueMaps.light.border)}
          ${swatchTile('Dark', token.dark, themeValueMaps.dark.border)}
        </div>
      </li>`
}).join('')

const evaluatedPairings = verifiedPairings.map((pairing) => {
  const lightContrast = contrast(themeValueMaps.light[pairing.foreground], themeValueMaps.light[pairing.background])
  const darkContrast = contrast(themeValueMaps.dark[pairing.foreground], themeValueMaps.dark[pairing.background])
  if (lightContrast < pairing.minimum || darkContrast < pairing.minimum) {
    throw new Error(`Verified pairing failed ${pairing.title}: ${formatRatio(lightContrast)} light / ${formatRatio(darkContrast)} dark`)
  }
  return { ...pairing, lightContrast, darkContrast }
})
const pairingGroups = [
  {
    key: 'text',
    title: 'Verified text pairings',
    note: 'Measured from the shared theme tokens at build time. These are the approved readable combinations — not every token can be mixed freely.',
  },
  {
    key: 'functional',
    title: 'Verified functional boundaries',
    note: 'Borders and focus indicators target at least 3:1 non-text contrast against the surfaces they appear on.',
  },
]
const pairingCards = (category) => evaluatedPairings
  .filter((pairing) => pairing.category === category)
  .map((pairing) => `
      <li class="${pairingCardCss}">
        <h4 class="${pairingTitleCss}">${pairing.title}</h4>
        <p class="${pairingTokenCss}">${tokenCode(pairing.foreground)} on ${tokenCode(pairing.background)}</p>
        <p class="${pairingBodyCss}">${pairing.note}</p>
        <p class="${pairingMetaCss}">Light ${formatRatio(pairing.lightContrast)} &middot; Dark ${formatRatio(pairing.darkContrast)} &middot; Target ${pairing.minimum}:1</p>
      </li>`).join('')

const tokenList = (items) => items.map((item) => `<code class="${scopeCodeCss}">${item}</code>`).join(', ')
const scopeList = (items) => items.map((item) => `<li>${item}</li>`).join('')
const typographyList = publicTokenScope.typography.sizes
  .map(({ token, fontSize, lineHeight }) => `<li><code class="${scopeCodeCss}">${token}</code> &mdash; ${fontSize} / ${lineHeight}</li>`)
  .join('')

const paletteHtml = `
<section id="palette" class="${bandCss}" aria-labelledby="palette-title">
  <div class="${wrapCss} ${sectionCss}">
    <p class="${eyebrowCss}">Palette</p>
    <h2 id="palette-title" class="${h2Css}">${themeTokenCount} colors, shown in both themes.</h2>
    <p class="${introCss}">One token set with a light and a dark value each. System mode follows <code class="${codeCss}">prefers-color-scheme</code>; explicit Light and Dark choices reuse the same tokens without a second stylesheet. Both values of every token are shown side by side.</p>
    ${paletteSections.map((section, index) => `
    <h3 class="${paletteGroupCss}${index ? ` ${paletteGapCss}` : ''}">${section.title}</h3>
    <p class="${paletteGroupNoteCss}">${section.note}</p>
    <ul class="${paletteGridCss}">${swatches(section.keys)}</ul>`).join('')}
    ${pairingGroups.map(({ key, title, note }) => `
    <h3 class="${paletteGroupCss} ${paletteGapCss}">${title}</h3>
    <p class="${paletteGroupNoteCss}">${note}</p>
    <ul class="${pairingGridCss}">${pairingCards(key)}</ul>`).join('')}
  </div>
</section>`

const tokensHtml = `
<section class="${wrapCss} ${sectionCss}" aria-labelledby="tokens-title">
  <p class="${eyebrowCss}">Public token scope</p>
  <h2 id="tokens-title" class="${h2Css}">What Verdant publishes, inherits, and keeps page-specific.</h2>
  <p class="${introCss}">The palette above defines the supported color API. These cards document the rest of the token surface so adopters can tell reusable design tokens from Panda defaults and demo-only layout values.</p>
  <div class="${scopeGridCss}">
    <section class="${scopeCardCss}">
      <h3 class="${scopeTitleCss}">Colors</h3>
      <p class="${scopeBodyCss}">Interface colors are the public text, control and status tokens. Illustration colors stay public for artwork only.</p>
      <ul class="${scopeListCss}">
        <li>Interface: ${tokenList(paletteSections[0].keys)}</li>
        <li>Illustration only: ${tokenList(paletteSections[1].keys)}</li>
      </ul>
    </section>
    <section class="${scopeCardCss}">
      <h3 class="${scopeTitleCss}">Spacing</h3>
      <p class="${scopeBodyCss}">Public spacing tokens follow a 4px rhythm.</p>
      <ul class="${scopeListCss}">${scopeList(publicTokenScope.spacing.map(({ token, value }) => `<code class="${scopeCodeCss}">${token}</code> &mdash; ${value}`))}</ul>
    </section>
    <section class="${scopeCardCss}">
      <h3 class="${scopeTitleCss}">Radii</h3>
      <p class="${scopeBodyCss}">Rounded corners stay on four reusable steps.</p>
      <ul class="${scopeListCss}">${scopeList(publicTokenScope.radii.map(({ token, value }) => `<code class="${scopeCodeCss}">${token}</code> &mdash; ${value}`))}</ul>
    </section>
    <section class="${scopeCardCss}">
      <h3 class="${scopeTitleCss}">Typography</h3>
      <p class="${scopeBodyCss}">System fonts plus six public size/line-height pairs.</p>
      <ul class="${scopeListCss}">
        ${scopeList(publicTokenScope.typography.families.map(({ token, value }) => `<code class="${scopeCodeCss}">${token}</code> &mdash; ${value}`))}
        ${typographyList}
      </ul>
    </section>
    <section class="${scopeCardCss}">
      <h3 class="${scopeTitleCss}">Layout &amp; breakpoints</h3>
      <p class="${scopeBodyCss}">Verdant keeps its public token surface small, so responsive and page-art values are called out separately here.</p>
      <ul class="${scopeListCss}">
        ${scopeList(publicTokenScope.layout.inherited)}
        ${scopeList(publicTokenScope.layout.pageSpecific)}
      </ul>
    </section>
  </div>
</section>`

// ---- index: saved WSG evidence --------------------------------------------------

const scoreListCss = css({ display: 'grid', gridTemplateColumns: { base: 'minmax(0, 1fr)', md: 'repeat(2, minmax(0, 1fr))' }, gap: '4', listStyle: 'none', margin: '0', padding: '0' })
const scoreItemCss = card()
const scoreHeadCss = flex({ justify: 'space-between', align: 'baseline', gap: '3', wrap: 'wrap' })
const scoreTitleCss = css({ fontSize: 'displaySm', lineHeight: 'displaySm', fontWeight: '600', margin: '0' })
const scorePassCss = css({ fontSize: 'label', lineHeight: 'label', fontWeight: '600', color: 'positive', margin: '0' })
const scoreOpenCss = css({ fontSize: 'label', lineHeight: 'label', fontWeight: '600', color: 'warning', margin: '0' })
const scorePendingCss = css({ fontSize: 'label', lineHeight: 'label', fontWeight: '600', color: 'ink.muted', margin: '0' })
const scoreBodyCss = css({ fontSize: 'bodySm', lineHeight: 'bodySm', color: 'ink.muted', margin: '8px 0 0' })
const scoreMetaCss = css({ fontSize: 'label', lineHeight: 'label', color: 'ink.muted', margin: '8px 0 0' })
const scoreNoteCss = css({ fontSize: 'bodySm', lineHeight: 'bodySm', color: 'ink.muted', marginTop: '6', maxWidth: '70ch' })
const scoreLinksCss = css({ fontSize: 'bodySm', lineHeight: 'bodySm', color: 'ink.muted', margin: '16px 0 0', maxWidth: '70ch' })

const statusCopy = {
  verified: { label: '&#10003; Verified', word: 'verified', css: scorePassCss },
  open: { label: '&#9888; Open', word: 'open', css: scoreOpenCss },
  'not-assessed': { label: '&#9675; Not assessed', word: 'not assessed', css: scorePendingCss },
  'not-applicable': { label: '&#8212; Not applicable', word: 'not applicable', css: scorePendingCss },
}
const statusOf = (entry) => statusCopy[entry.status] || statusCopy['not-assessed']
const linkSummary = (records = []) => records.map((record) => `<a href="${record.href}">${record.label}</a>`).join(', ')
// Every status the record can hold is counted, in a fixed order, so the
// summary always adds up to the number of cards below it.
const statusSummary = Object.keys(statusCopy)
  .map((key) => [key, evidenceRecord.entries.filter((entry) => statusOf(entry) === statusCopy[key]).length])
  .filter(([, count]) => count)
  .map(([key, count]) => `${count} ${statusCopy[key].word}`)
  .join(', ')
const scoreHtml = `
<section class="${wrapCss} ${sectionCss}" aria-labelledby="score-title">
  <p class="${eyebrowCss}">Saved evidence record</p>
  <h2 id="score-title" class="${h2Css}">Implementation checklist for selected WSG-aligned defaults.</h2>
  <p class="${introCss}">${evidenceRecord.title} reviewed on ${evidenceRecord.reviewed_on} (${statusSummary}). This section is generated from a saved artifact, not a live deploy audit, and it documents selected evidence rather than full WSG conformance.</p>
  <p class="${scoreLinksCss}">Linked records: ${linkSummary(evidenceRecord.related_records)}</p>
  <ul class="${scoreListCss}">
    ${evidenceRecord.entries.map((entry) => `
    <li class="${scoreItemCss}">
      <div class="${scoreHeadCss}">
        <h3 class="${scoreTitleCss}">${entry.scanner_category}</h3>
        <p class="${statusOf(entry).css}">${statusOf(entry).label}</p>
      </div>
      <p class="${scoreBodyCss}">${entry.summary}</p>
      <p class="${scoreMetaCss}">Reviewed ${entry.date} &middot; ${evidenceRecord.wsg_edition.label} &middot; ${entry.wsg_refs.length ? `WSG refs ${entry.wsg_refs.join(', ')}` : 'No WSG section claimed'}</p>
      <p class="${scoreMetaCss}">Scope: ${entry.scope}</p>
      <p class="${scoreMetaCss}">${entry.tool.version ? `Tool: ${entry.tool.name} (${entry.tool.version})` : `Tool: ${entry.tool.name}`} &middot; <a href="${entry.evidence_link}">Evidence link</a></p>
      ${entry.linked_records?.length ? `<p class="${scoreMetaCss}">Linked records: ${linkSummary(entry.linked_records)}</p>` : ''}
    </li>`).join('')}
  </ul>
  <p class="${scoreNoteCss}">The card headings follow <a href="${WSG_CHECK}">wsg-check</a>'s scanner categories, not the WSG section structure. Status is always a word plus a symbol, never color alone, and the full record is also available as <a href="/wsg-evidence.json">JSON</a>.</p>
</section>`

// ---- index: PandaCSS ------------------------------------------------------------

const pandaGridCss = css({ display: 'grid', gridTemplateColumns: { base: '1fr', md: '1fr 1.2fr' }, gap: { base: '6', md: '12' }, alignItems: 'start' })
const preCss = css({
  fontFamily: 'mono', fontSize: 'label', lineHeight: '20px', margin: '0',
  background: 'surface.100', color: 'ink', border: '1px solid', borderColor: 'border',
  borderRadius: 'md', padding: '4', overflowX: 'auto',
})
const listCss = css({ margin: '0', paddingLeft: '20px', listStyle: 'disc', color: 'ink.muted', '& li + li': { marginTop: '2' } })
const pandaSnippet = `// panda.config.ts
conditions: {
  dark: '@media (prefers-color-scheme: dark)',
},
theme: { extend: { semanticTokens: { colors: {
  accent: { value: { base: '#2f6b4a', _dark: '#7fcfa3' } },
  // …the other ${themeTokenCount - 1}, same shape
} } } },
// No staticCss: ship only the rules pages use.`
const escapeHtml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

const pandaHtml = `
<section class="${bandCss}" aria-labelledby="panda-title">
  <div class="${wrapCss} ${sectionCss}">
    <div class="${pandaGridCss}">
      <div>
        <p class="${eyebrowCss}">Built with PandaCSS</p>
        <h2 id="panda-title" class="${h2Css}">Tokens in, only-what-you-use CSS out.</h2>
        <p class="${introCss}">Verdant fits in one <a href="https://panda-css.com">PandaCSS</a> config. Build-time extraction keeps the stylesheet tied to what the page actually renders.</p>
        <ul class="${listCss}">
          <li>Semantic tokens carry both themes; <code class="${codeCss}">_dark</code> maps to the OS preference.</li>
          <li>Recipes for button, card, field and switch mirror the component guidelines.</li>
          <li>No runtime CSS-in-JS reaches the browser.</li>
        </ul>
      </div>
      <pre class="${preCss}" tabindex="0" aria-label="Example panda.config.ts"><code>${escapeHtml(pandaSnippet)}</code></pre>
    </div>
  </div>
</section>`

// ---- index: CTA band --------------------------------------------------------------

const ctaCss = css({ background: 'accent', color: 'accent.ink', position: 'relative', overflow: 'hidden' })
const ctaInnerCss = css({ position: 'relative', paddingBlock: { base: '12', md: '16' } })
const ctaTitleCss = css({ fontSize: { base: 'displayMd', md: 'displayLg' }, lineHeight: { base: 'displayMd', md: 'displayLg' }, fontWeight: '700', margin: '0', maxWidth: '22ch' })
const ctaBodyCss = css({ margin: '12px 0 0', maxWidth: '56ch' })
const ctaBtnCss = css({
  display: 'inline-flex', alignItems: 'center', justifyContent: 'center', minHeight: '44px', fontSize: 'bodySm', lineHeight: 'bodySm', fontWeight: '600', letterSpacing: '0.02em',
  paddingBlock: '3', paddingInline: '4', borderRadius: 'md', textDecoration: 'none',
  background: 'accent.ink', color: 'accent', border: '1px solid', borderColor: 'accent.ink',
  _hover: { color: 'accent.strong' },
  _focusVisible: { outline: '2px solid', outlineColor: 'accent.ink', outlineOffset: '3px' },
})
const ctaLinkCss = css({
  display: 'inline-flex', alignItems: 'center', justifyContent: 'center', minHeight: '44px', fontSize: 'bodySm', lineHeight: 'bodySm', fontWeight: '600', letterSpacing: '0.02em',
  paddingBlock: '3', paddingInline: '4', borderRadius: 'md', textDecoration: 'none',
  color: 'accent.ink', border: '1px solid', borderColor: 'accent.ink',
  _hover: { color: 'accent.ink', textDecoration: 'underline' },
  _focusVisible: { outline: '2px solid', outlineColor: 'accent.ink', outlineOffset: '3px' },
})
const ctaArtCss = css({ position: 'absolute', right: '0', bottom: '0', width: '600px', maxWidth: '100%', pointerEvents: 'none', '& svg': { display: 'block', width: '100%', height: 'auto' } })

const ctaHtml = `
<section class="${ctaCss}" aria-labelledby="cta-title">
  <div class="${ctaArtCss}">${leafRow()}</div>
  <div class="${wrapCss} ${ctaInnerCss}">
    <h2 id="cta-title" class="${ctaTitleCss}">Use it in your next project.</h2>
    <p class="${ctaBodyCss}">Clone the repo, copy <code class="${codeCss}">panda.config.ts</code>, and keep the checklist. Start with the defaults, then layer in only the styling your product needs.</p>
    <div class="${btnRowCss}">
      <a class="${ctaBtnCss}" href="${REPO}">Get the source</a>
      <a class="${ctaLinkCss}" href="${COMPONENTS_ROUTE}">See the components</a>
    </div>
  </div>
</section>`

// ---- page shell -----------------------------------------------------------------

const nav = (active) => {
  const link = (key, href, label) =>
    `<li><a class="${active === key ? navLinkActiveCss : navLinkCss}" href="${href}"${active === key ? ' aria-current="page"' : ''}>${label}</a></li>`
  const themeOption = (value, label) => `
          <label class="${themePrefOptionCss}" for="theme-pref-${value}">
            <input class="${themePrefRadioCss}" type="radio" id="theme-pref-${value}" name="${themePreferenceControlName}" value="${value}"${value === themePreferenceValues[0] ? ' checked' : ''}>
            <span>${label}</span>
          </label>`
  return `
  <header class="${headerCss}">
    <div class="${wrapCss} ${barCss}">
      <a class="${wordmarkCss}" href="/">${mark(28)}<span>Verdant</span></a>
      <div class="${headerActionsCss}">
        <nav aria-label="Primary">
          <ul class="${navListCss}">
            ${link('components', COMPONENTS_ROUTE, 'Components')}
            ${link('palette', '/#palette', 'Palette')}
            ${link('github', REPO, 'GitHub')}
          </ul>
        </nav>
        <fieldset class="${themePrefCss}" aria-label="Theme preference">
          <legend class="${themePrefLegendCss}">Theme</legend>
          ${themeOption('system', 'System')}
          ${themeOption('light', 'Light')}
          ${themeOption('dark', 'Dark')}
        </fieldset>
      </div>
    </div>
  </header>`
}

const breadcrumb = (label) => `
  <nav class="${wrapCss}" aria-label="Breadcrumb">
    <ol class="${breadcrumbListCss}">
      <li><a class="${breadcrumbLinkCss}" href="/">Home</a></li>
      <li aria-hidden="true">/</li>
      <li aria-current="page">${label}</li>
    </ol>
  </nav>`

const footer = () => `
  <footer class="${footerCss}">
    <div class="${wrapCss} ${footerBarCss}">
      <div class="${footerBrandCss}">${mark(20)}<p class="${footerTextCss}">Verdant &mdash; built by Ivan with PandaCSS, with defaults aligned to selected Web Sustainability Guidelines.</p></div>
      <ul class="${footerLinksCss}">
        <li><a href="${WSG_CHECK}">wsg-check</a></li>
        <li><a href="${REPO}">Source</a></li>
      </ul>
    </div>
  </footer>`

const updateBannerCss = css({
  position: 'fixed',
  insetInline: { base: '4', md: '6' },
  bottom: { base: '4', md: '6' },
  zIndex: '10',
  maxWidth: '640px',
  marginInline: 'auto',
  padding: '4',
  background: 'surface.200',
  border: '1px solid',
  borderColor: 'border',
  borderRadius: 'md',
  boxShadow: 'md',
})
const updateBannerTextCss = css({ margin: '0', fontSize: 'bodySm', lineHeight: 'bodySm', color: 'ink' })
const updateBannerActionsCss = hstack({ gap: '3', marginTop: '3', flexWrap: 'wrap' })

const updateBanner = `
  <section id="sw-update" class="${updateBannerCss}" hidden aria-labelledby="sw-update-title" aria-live="polite" aria-atomic="true">
    <p id="sw-update-title" class="${updateBannerTextCss}">A fresh Verdant update is ready. Apply it when you&rsquo;re ready.</p>
    <div class="${updateBannerActionsCss}">
      <button id="sw-update-apply" type="button" class="${btnPrimary}">Update now</button>
      <button id="sw-update-dismiss" type="button" class="${btnSecondary}">Later</button>
    </div>
  </section>`

const page = ({ title, description, path, active, jsonLd, bodyHtml, scripts = [] }) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<meta name="description" content="${description}">
<link rel="canonical" href="https://verdant-wsg-demo.netlify.app${path}">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${description}">
<meta property="og:type" content="website">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="manifest" href="/manifest.json">
<meta name="theme-color" content="${themeTokens['surface.100'].light}" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="${themeTokens['surface.100'].dark}" media="(prefers-color-scheme: dark)">
<script src="/theme-toggle.js"></script>
<link rel="stylesheet" href="/styles.css">
${jsonLd ? `<script type="application/ld+json">${JSON.stringify(jsonLd)}</script>` : ''}
</head>
<body>
<a class="${skipLinkCss}" href="#main">Skip to content</a>
${nav(active)}
${active === 'components' ? breadcrumb('Components') : ''}
<main id="main">
${bodyHtml}
</main>
${footer()}
${updateBanner}
${['/sw-register.js', ...scripts].map((s) => `<script src="${s}" defer></script>`).join('\n')}
</body>
</html>
`

// ---- components.html --------------------------------------------------------------

const compMainCss = css({ paddingBlock: { base: '8', md: '12' } })
const compTitleCss = css({ fontSize: { base: '40px', md: '56px' }, lineHeight: '1', fontWeight: '700', letterSpacing: '-0.01em', margin: '0 0 16px' })
const compSectionCss = css({ marginTop: '12' })
const compH2Css = css({ fontSize: 'displayMd', lineHeight: 'displayMd', fontWeight: '700', margin: '0' })
const ledeCss = css({ color: 'ink.muted', maxWidth: '62ch', margin: '0' })
const gridCss = css({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '4' })
const cardCss = card()
const cardHeadingCss = css({ fontSize: 'displaySm', lineHeight: 'displaySm', fontWeight: '600', margin: '0 0 4px' })
const cardBodyCss = css({ color: 'ink.muted', margin: '0', fontSize: 'bodySm', lineHeight: 'bodySm' })
const statusCss = hstack({ gap: '1', fontSize: 'label', lineHeight: 'label', fontWeight: '600', marginTop: '3' })
const statusPositiveCss = css({ color: 'positive' })
const statusInfoCss = css({ color: 'info' })
const statusWarningCss = css({ color: 'warning' })
const statusCriticalCss = css({ color: 'critical' })
const rowCss = flex({ gap: '3', align: 'center', wrap: 'wrap' })
const captionCss = css({ fontSize: 'label', color: 'ink.muted', margin: '0' })
const formCss = vstack({ gap: '3', alignItems: 'stretch', width: '100%', maxWidth: '360px' })
// stretch: hints and errors match the input's width, even on narrow screens
const fieldCss = vstack({ gap: '1', alignItems: 'stretch', width: '100%' })
const labelCss = css({ fontSize: 'label', lineHeight: 'label', fontWeight: '600' })
const hintCss = css({ fontSize: 'bodySm', color: 'ink.muted', margin: '0' })
const inputCss = fieldInput()
const switchRowCss = flex({ align: 'center', gap: '3' })
const switchOffCss = switchTrack()
const switchOnCss = switchTrack({ on: true })
const noteCss = css({ marginTop: '3', fontSize: 'label', color: 'ink.muted', maxWidth: '60ch' })
const motionRowCss = flex({ align: 'center', gap: '6', wrap: 'wrap' })
const motionGroupCss = vstack({ gap: '2', alignItems: 'flex-start' })
const spinnerCss = spinner()
const spinnerPreviewCss = spinner({ preview: true })
// Widths live in classes, not style="" — the CSP's style-src 'self' blocks
// inline style attributes, which silently collapsed these bars before.
const skeletonWideCss = `${skeleton()} ${css({ width: '160px', height: '14px' })}`
const skeletonWidePreviewCss = `${skeleton({ preview: true })} ${css({ width: '160px', height: '14px' })}`
const skeletonNarrowCss = `${skeleton()} ${css({ width: '110px', height: '14px' })}`
const skeletonNarrowPreviewCss = `${skeleton({ preview: true })} ${css({ width: '110px', height: '14px' })}`
const motionIntroCss = css({ color: 'ink.muted', maxWidth: '62ch', margin: '0 0 16px' })
const motionControlsCss = flex({ align: 'center', gap: '3', wrap: 'wrap', marginTop: '4' })
// minmax(0, 1fr) keeps a wide fallback font from stretching the column past a 320px viewport.
const specimenGridCss = css({ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr)', gap: '6' })
const specimenCss = css({ background: 'surface.200', border: '1px solid', borderColor: 'border', borderRadius: 'lg', padding: { base: '4', md: '6' }, display: 'grid', gridTemplateColumns: 'minmax(0, 1fr)', gap: '4' })
const specimenHeaderCss = vstack({ gap: '2', alignItems: 'flex-start' })
const specimenLabelCss = css({ fontSize: 'label', lineHeight: 'label', fontWeight: '600', letterSpacing: '0.02em', color: 'accent', margin: '0' })
const specimenBlockCss = vstack({ gap: '2', alignItems: 'stretch' })
const specimenPreviewCss = css({ border: '1px solid', borderColor: 'border', borderRadius: 'md', background: 'surface.100', padding: '4' })
const specimenStateGridCss = css({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '3' })
const specimenStateCss = css({ border: '1px dashed', borderColor: 'border', borderRadius: 'md', padding: '3', display: 'grid', gap: '2', alignContent: 'start' })
const specimenStateTitleCss = css({ fontSize: 'label', lineHeight: 'label', fontWeight: '600', margin: '0' })
const specimenStateBodyCss = css({ display: 'grid', gap: '2' })
const specimenListCss = css({ margin: '0', paddingInlineStart: '20px', color: 'ink.muted', display: 'grid', gap: '1' })
const specimenCodeStackCss = css({ display: 'grid', gap: '2' })
const specimenDetailsCss = css({ border: '1px solid', borderColor: 'border', borderRadius: 'md', background: 'surface.100' })
const specimenSummaryCss = css({ cursor: 'pointer', paddingInline: '3', paddingBlock: '2', fontSize: 'label', lineHeight: 'label', fontWeight: '600' })
const specimenPreCss = css({ margin: '0', paddingInline: '3', paddingBottom: '3', overflowX: 'auto', fontFamily: 'mono', fontSize: 'label', lineHeight: 'label', whiteSpace: 'pre-wrap' })
const prosePreviewCss = css({ margin: '0', maxWidth: '48ch' })
const proseLinkCss = css({
  color: 'accent',
  textDecoration: 'underline',
  textUnderlineOffset: '3px',
  textDecorationThickness: '1.5px',
  _hover: { color: 'accent.strong' },
  _visited: { color: 'accent.strong' },
})
const demoVisitedCss = css({ color: 'accent.strong' })
const demoFocusCss = css({ outline: '2px solid', outlineColor: 'focusRing', outlineOffset: '2px' })
const demoPrimaryHoverCss = css({ background: 'accent.strong' })
const inputErrorCss = css({ borderColor: 'critical' })
const inputSuccessCss = css({ borderColor: 'positive' })
const successTextCss = css({ fontSize: 'bodySm', color: 'positive', margin: '0' })
const errorTextCss = css({ fontSize: 'bodySm', color: 'critical', margin: '0' })
const previewStackCss = vstack({ gap: '4', alignItems: 'stretch' })
const loadingFrameCss = css({ border: '1px dashed', borderColor: 'border', borderRadius: 'md', padding: '4', display: 'grid', gap: '3', maxWidth: '300px' })
const switchDisabledCss = css({ opacity: '0.55', cursor: 'not-allowed' })

const snippet = (label, code) => `
<details class="${specimenDetailsCss}">
  <summary class="${specimenSummaryCss}">${label}</summary>
  <pre class="${specimenPreCss}"><code>${escapeHtml(code.trim())}</code></pre>
</details>`

const stateTile = (title, body, note = '') => `
<div class="${specimenStateCss}">
  <p class="${specimenStateTitleCss}">${title}</p>
  <div class="${specimenStateBodyCss}">${body}</div>
  ${note ? `<p class="${captionCss}">${note}</p>` : ''}
</div>`

const specimen = ({ id, title, blurb, preview, states, guidance, htmlCode, pandaCode }) => `
<section class="${specimenCss}" aria-labelledby="${id}-title">
  <header class="${specimenHeaderCss}">
    <h2 id="${id}-title" class="${compH2Css}">${title}</h2>
    <p class="${cardBodyCss}">${blurb}</p>
  </header>
  <div class="${specimenBlockCss}">
    <p class="${specimenLabelCss}">Preview</p>
    <div class="${specimenPreviewCss}">${preview}</div>
  </div>
  <div class="${specimenBlockCss}">
    <p class="${specimenLabelCss}">State examples</p>
    <div class="${specimenStateGridCss}">${states}</div>
  </div>
  <div class="${specimenBlockCss}">
    <p class="${specimenLabelCss}">Usage guidance</p>
    <ul class="${specimenListCss}">
      ${guidance.map((item) => `<li>${item}</li>`).join('')}
    </ul>
  </div>
  <div class="${specimenBlockCss}">
    <p class="${specimenLabelCss}">Copyable examples</p>
    <div class="${specimenCodeStackCss}">
      ${snippet('HTML', htmlCode)}
      ${snippet('Panda', pandaCode)}
    </div>
  </div>
</section>`

const componentsBody = `
<div class="${wrapCss} ${compMainCss}">
  <h1 class="${compTitleCss}">Components</h1>
  <p class="${ledeCss}">Six documented specimens pair preview states, concise guidance, and copyable snippets without implying a live backend. The site-wide System/Light/Dark preference lives in the header.</p>

  <div class="${specimenGridCss} ${compSectionCss}">
    ${specimen({
      id: 'link-specimen',
      title: 'Links',
      blurb: 'Use anchors for navigation in prose. The gallery keeps a deliberate visited style and leaves keyboard focus to the browser.',
      preview: `
        <p class="${prosePreviewCss}">
          Read the <a class="${proseLinkCss}" href="#field-specimen-title">field guidance</a>,
          revisit the <a class="${proseLinkCss}" href="#status-specimen-title">sample scan findings</a>,
          or inspect the <a class="${proseLinkCss} ${demoFocusCss}" href="#loading-specimen-title">loading specimen</a>.
        </p>
        <p class="${noteCss}">Visited styling appears after your browser records a destination, so the sample above uses real anchors instead of a fake disabled link.</p>`,
      states: [
        stateTile('Default', `<a class="${proseLinkCss}" href="#button-specimen-title">Browse button guidance</a>`),
        stateTile('Visited tone', `<a class="${proseLinkCss} ${demoVisitedCss}" href="#status-specimen-title">Revisit sample results</a>`, 'Browser-controlled once followed.'),
        stateTile('Focus-visible', `<a class="${proseLinkCss} ${demoFocusCss}" href="#switch-specimen-title">Move to the switch specimen</a>`, 'Tab to links; Enter follows them.'),
      ].join(''),
      guidance: [
        'Keep link text specific to the destination instead of repeating “click here.”',
        'Visited styling is intentional for prose links so readers can tell which references they have opened.',
        'Never present navigation as disabled; if an action is unavailable, use a button or explanatory text instead.',
      ],
      htmlCode: `
<p>
  Read the <a href="#field-specimen-title">field guidance</a>.
</p>`,
      pandaCode: `
const proseLink = css({
  color: 'accent',
  textDecoration: 'underline',
  textUnderlineOffset: '3px',
  _visited: { color: 'accent.strong' },
})`,
    })}

    ${specimen({
      id: 'button-specimen',
      title: 'Buttons',
      blurb: 'Buttons stay native for actions. Show a pressed state only on toggle buttons, and use the disabled attribute when the action truly cannot run.',
      preview: `
        <div class="${rowCss}">
          <button class="${btnPrimary}" type="button">Save changes</button>
          <button class="${btnSecondary}" type="button">Cancel</button>
          <button class="${btnPrimary}" type="button" aria-pressed="true">Updates enabled</button>
        </div>
        <p class="${noteCss}">The pressed example is a toggle button specimen only; ordinary submit buttons should not use <code class="${codeCss}">aria-pressed</code>.</p>`,
      states: [
        stateTile('Default', `<button class="${btnPrimary}" type="button">Run sample scan</button>`),
        stateTile('Hover', `<button class="${btnPrimary} ${demoPrimaryHoverCss}" type="button">Run sample scan</button>`, 'Hover should reinforce the action without changing the label.'),
        stateTile('Focus-visible', `<button class="${btnSecondary} ${demoFocusCss}" type="button">Review changes</button>`, 'Tab to buttons; Space or Enter activates them.'),
        stateTile('Pressed toggle', `<button class="${btnPrimary}" type="button" aria-pressed="true">Sample alerts on</button>`, 'Use only when the button keeps an on/off state.'),
        stateTile('Disabled', `<button class="${btnPrimary}" type="button" disabled>Scan unavailable</button>`, 'Disabled buttons are skipped by keyboard focus.'),
      ].join(''),
      guidance: [
        'Choose links for navigation and buttons for in-page actions or form submission.',
        `Only persistent toggles should use <code class="${codeCss}">aria-pressed</code>; one-off actions stay unpressed.`,
        'Disabled buttons should explain why elsewhere when the next step is not obvious.',
      ],
      htmlCode: `
<button type="button" aria-pressed="true">
  Sample alerts on
</button>`,
      pandaCode: `
const actionButton = button({ variant: 'primary' })
const quietButton = button({ variant: 'secondary' })`,
    })}

    ${specimen({
      id: 'field-specimen',
      title: 'Fields',
      blurb: 'Single-field forms still need associated hints, actionable errors, and room for read-only or success states.',
      preview: `
        <form class="${formCss}">
          <div class="${fieldCss}">
            <label class="${labelCss}" for="site-url">Website URL <span aria-hidden="true">*</span></label>
            <input class="${inputCss}" id="site-url" name="url" type="url" inputmode="url" autocomplete="url" placeholder="https://example.com" required aria-describedby="site-url-hint">
            <p class="${hintCss}" id="site-url-hint">Use a full <code class="${codeCss}">https://</code> URL for this static example.</p>
          </div>
        </form>`,
      states: [
        stateTile('Required', `
          <label class="${labelCss}" for="site-url-required">Website URL <span aria-hidden="true">*</span></label>
          <input class="${inputCss}" id="site-url-required" type="url" required aria-describedby="site-url-required-hint" placeholder="https://example.com">
          <p class="${hintCss}" id="site-url-required-hint">Hints match the input width on narrow screens.</p>`),
        stateTile('Error', `
          <label class="${labelCss}" for="site-url-error">Website URL <span aria-hidden="true">*</span></label>
          <input class="${inputCss} ${inputErrorCss}" id="site-url-error" type="url" aria-invalid="true" aria-describedby="site-url-error-hint site-url-error-note" value="verdant.example">
          <p class="${hintCss}" id="site-url-error-hint">Provide a reachable sample URL.</p>
          <p class="${errorTextCss}" id="site-url-error-note">&#9888; Add <code class="${codeCss}">https://</code> so the address is complete.</p>`),
        stateTile('Read-only success', `
          <label class="${labelCss}" for="site-url-readonly">Website URL</label>
          <input class="${inputCss} ${inputSuccessCss}" id="site-url-readonly" type="url" readonly aria-describedby="site-url-readonly-note" value="https://verdant.example">
          <p class="${successTextCss}" id="site-url-readonly-note">&#10003; Sample target saved for the next review.</p>`),
      ].join(''),
      guidance: [
        `Keep every hint and error associated with the field through <code class="${codeCss}">aria-describedby</code>.`,
        'Error text should explain the fix, not just restate that something is invalid.',
        'Read-only fields remain focusable and selectable, which helps people copy sample values.',
      ],
      htmlCode: `
<label for="site-url">Website URL</label>
<input id="site-url" type="url" aria-invalid="true"
  aria-describedby="site-url-hint site-url-error">
<p id="site-url-hint">Provide a reachable URL.</p>
<p id="site-url-error">Add https:// so the address is complete.</p>`,
      pandaCode: `
const field = fieldInput()
const invalidField = css({ borderColor: 'critical' })
const successField = css({ borderColor: 'positive' })`,
    })}

    ${specimen({
      id: 'switch-specimen',
      title: 'Switches',
      blurb: 'Switches represent an immediate on/off setting. The track and knob follow aria-checked, so visual and announced state cannot drift.',
      preview: `
        <div class="${previewStackCss}">
          <div>
            <p class="${captionCss}">Live specimen</p>
            <div class="${switchRowCss}">
              <button type="button" class="${switchOffCss}" role="switch" aria-checked="false" aria-labelledby="specimen-switch-label" id="theme-switch">
                <span class="knob"></span>
              </button>
              <span class="${labelCss}" id="specimen-switch-label">Email alerts</span>
            </div>
          </div>
          <p class="${noteCss}">Demonstration only: the site-wide System/Light/Dark preference lives in the header. This specimen keeps its track and knob in sync with its own state.</p>
        </div>`,
      states: [
        stateTile('Off', `
          <div class="${switchRowCss}">
            <button type="button" class="${switchOffCss}" role="switch" aria-checked="false" aria-labelledby="switch-state-off">
              <span class="knob"></span>
            </button>
            <span class="${captionCss}" id="switch-state-off">Motion follows system</span>
          </div>`),
        stateTile('On', `
          <div class="${switchRowCss}">
            <button type="button" class="${switchOnCss}" role="switch" aria-checked="true" aria-labelledby="switch-state-on">
              <span class="knob"></span>
            </button>
            <span class="${captionCss}" id="switch-state-on">Email alerts on</span>
          </div>`, `Use <code class="${codeCss}">aria-checked</code> to expose state.`),
        stateTile('Disabled', `
          <div class="${switchRowCss}">
            <button type="button" class="${switchOffCss} ${switchDisabledCss}" role="switch" aria-checked="false" aria-labelledby="switch-state-disabled" disabled>
              <span class="knob"></span>
            </button>
            <span class="${captionCss}" id="switch-state-disabled">Locked by policy</span>
          </div>`, 'Space toggles switches; disabled ones stay inert.'),
      ].join(''),
      guidance: [
        'Use switches for immediate preferences, not deferred form submissions.',
        `A switch needs a visible label plus <code class="${codeCss}">aria-checked</code> to announce its state.`,
        `Native buttons already support Space and Enter, so <code class="${codeCss}">role="switch"</code> can build on that behavior.`,
      ],
      htmlCode: `
<button type="button" role="switch" aria-checked="false"
  aria-labelledby="alerts-label">
  <span class="knob"></span>
</button>
<span id="alerts-label">Email alerts</span>`,
      pandaCode: `
const switchOff = switchTrack()
const switchOn = switchTrack({ on: true })`,
    })}

    ${specimen({
      id: 'status-specimen',
      title: 'Cards and status',
      blurb: 'Sample scan cards stay obviously static. Icons and text communicate state together so the specimen does not rely on color alone.',
      preview: `
        <p class="${captionCss}">Sample scan results</p>
        <div class="${gridCss}">
          <div class="${cardCss}">
            <p class="${captionCss}">Sample result</p>
            <h3 class="${cardHeadingCss}">Homepage scan</h3>
            <p class="${cardBodyCss}">18 checks passed, 2 warnings, 0 failures.</p>
            <div class="${statusCss} ${statusPositiveCss}"><span aria-hidden="true">&#10003;</span><span>Passing sample</span></div>
          </div>
          <div class="${cardCss}">
            <p class="${captionCss}">Sample result</p>
            <h3 class="${cardHeadingCss}">Checkout flow</h3>
            <p class="${cardBodyCss}">Render-blocking script appears on the payment step.</p>
            <div class="${statusCss} ${statusWarningCss}"><span aria-hidden="true">&#9888;</span><span>Needs attention</span></div>
          </div>
        </div>`,
      states: [
        stateTile('Passing', `
          <div class="${cardCss}">
            <h3 class="${cardHeadingCss}">Accessibility summary</h3>
            <p class="${cardBodyCss}">Keyboard checks passed in this sample.</p>
            <div class="${statusCss} ${statusPositiveCss}"><span aria-hidden="true">&#10003;</span><span>Passing sample</span></div>
          </div>`),
        stateTile('Informational', `
          <div class="${cardCss}">
            <h3 class="${cardHeadingCss}">Queue note</h3>
            <p class="${cardBodyCss}">This card shows static copy only; no network request has been sent.</p>
            <div class="${statusCss} ${statusInfoCss}"><span aria-hidden="true">&#9432;</span><span>Sample only</span></div>
          </div>`),
        stateTile('Warning', `
          <div class="${cardCss}">
            <h3 class="${cardHeadingCss}">Images review</h3>
            <p class="${cardBodyCss}">One decorative image still needs an empty alt attribute.</p>
            <div class="${statusCss} ${statusWarningCss}"><span aria-hidden="true">&#9888;</span><span>Review before publish</span></div>
          </div>`),
        stateTile('Critical', `
          <div class="${cardCss}">
            <h3 class="${cardHeadingCss}">Form submission</h3>
            <p class="${cardBodyCss}">The contact form posts to an endpoint that returns an error.</p>
            <div class="${statusCss} ${statusCriticalCss}"><span aria-hidden="true">&#10005;</span><span>Blocks publish</span></div>
          </div>`),
      ].join(''),
      guidance: [
        'Label examples as samples whenever the page is not showing live application data.',
        'Pair status color with an icon or word so the meaning survives monochrome and high-contrast modes.',
        `Match the token to the stakes: ${tokenCode('info')} for neutral notes, ${tokenCode('warning')} for cautions that do not block, ${tokenCode('critical')} only for errors and destructive actions.`,
        'Keep the card body focused on the next action or takeaway instead of reproducing raw scanner output.',
      ],
      htmlCode: `
<article class="card">
  <h3>Homepage scan</h3>
  <p>18 checks passed, 2 warnings, 0 failures.</p>
  <p>✓ Passing sample</p>
</article>`,
      pandaCode: `
const resultCard = card()
const passingStatus = css({ color: 'positive' })
const infoStatus = css({ color: 'info' })
const warningStatus = css({ color: 'warning' })
const criticalStatus = css({ color: 'critical' })`,
    })}

    ${specimen({
      id: 'loading-specimen',
      title: 'Loading patterns',
      blurb: 'Loading feedback is bounded, labelled, and explicitly demo-only. Nothing animates until you ask, and reduced motion keeps it still.',
      preview: `
        <p class="${motionIntroCss}">Static by default. The preview runs four spinner turns and three skeleton pulses (about four seconds), then stops. With reduced motion requested, the examples stay still.</p>
        <div class="${motionRowCss}">
          <div class="${loadingFrameCss}">
            <div class="${statusCss}">
              <div id="demo-spinner" class="${spinnerCss}" aria-hidden="true"></div>
              <span>Preparing sample scan results</span>
            </div>
            <p class="${captionCss}">Example only &mdash; this gallery does not start a backend scan.</p>
          </div>
          <div class="${loadingFrameCss}">
            <div class="${motionGroupCss}">
              <div id="demo-skeleton-wide" class="${skeletonWideCss}" aria-hidden="true"></div>
              <div id="demo-skeleton-narrow" class="${skeletonNarrowCss}" aria-hidden="true"></div>
            </div>
            <p class="${captionCss}">Use skeletons for known layout while content is on the way.</p>
          </div>
        </div>
        <div class="${motionControlsCss}">
          <button class="${btnSecondary}" type="button" id="motion-preview">Preview loading motion</button>
        </div>
        <p class="${noteCss}" id="motion-preview-status" role="status" aria-live="polite">Static by default. Preview runs once, then stops automatically.</p>`,
      states: [
        stateTile('Spinner', `<div class="${statusCss}"><div class="${spinnerCss}" aria-hidden="true"></div><span>Loading sample data</span></div>`, 'Pair any indicator with text; the text carries the meaning.'),
        stateTile('Skeleton', `<div class="${motionGroupCss}"><div class="${skeletonWideCss}" aria-hidden="true"></div><div class="${skeletonNarrowCss}" aria-hidden="true"></div></div>`, 'Decorative placeholders stay out of the accessibility tree.'),
        stateTile('Disabled while loading', `<button class="${btnPrimary}" type="button" disabled>Preparing report</button>`, 'Reserve disabled loading buttons for actions already in progress.'),
      ].join(''),
      guidance: [
        'Announce active work with text, not with motion alone.',
        'Keep loading indicators inside the region they describe so users can tell what is pending.',
        'If the layout is already known, skeletons can reduce surprise while content arrives.',
      ],
      htmlCode: `
<div role="status" aria-label="Loading sample results"></div>
<p>Preparing sample scan results</p>`,
      pandaCode: `
const busySpinner = spinner()
const loadingSkeleton = skeleton()`,
    })}

  </div>
</div>
`

// ---- 404 ----------------------------------------------------------------------

const nfCss = vstack({ gap: '4', alignItems: 'flex-start', paddingBlock: { base: '12', md: '16' } })
const notFoundBody = `
<div class="${wrapCss} ${nfCss}">
  ${seedlingArt()}
  <h1 class="${compTitleCss}">Page not found</h1>
  <p class="${ledeCss}">Nothing has grown here yet. <a href="/">Back to the overview</a>, or <a href="${COMPONENTS_ROUTE}">browse the components</a>.</p>
</div>`

const offlineBody = `
<div class="${wrapCss} ${nfCss}">
  ${seedlingArt()}
  <h1 class="${compTitleCss}">Offline for now</h1>
  <p class="${ledeCss}">This page isn&rsquo;t cached yet, and the network is out of reach. You can still open the <a href="/">overview</a> or the <a href="${COMPONENTS_ROUTE}">component gallery</a>, which are saved for offline use after installation.</p>
</div>`

// ---- scripts ---------------------------------------------------------------------

const themeToggleJs = `(function () {
  var STORAGE_KEY = ${JSON.stringify(themePreferenceStorageKey)};
  var OVERRIDE_ATTR = ${JSON.stringify(themeOverrideAttr)};
  var PREFERENCE_ATTR = ${JSON.stringify(themePreferenceAttr)};
  var RESOLVED_ATTR = ${JSON.stringify(themeResolvedAttr)};
  var CONTROL_NAME = ${JSON.stringify(themePreferenceControlName)};
  var SWITCH_OFF = ${JSON.stringify(switchOffCss)};
  var SWITCH_ON = ${JSON.stringify(switchOnCss)};
  var media = window.matchMedia ? window.matchMedia("(prefers-color-scheme: dark)") : null;
  function systemTheme() {
    return media && media.matches ? "dark" : "light";
  }
  function readPreference() {
    try {
      var saved = window.localStorage.getItem(STORAGE_KEY);
      if (saved === "light" || saved === "dark") return saved;
    } catch (_) {}
    return "system";
  }
  function persistPreference(value) {
    try {
      if (value === "system") window.localStorage.removeItem(STORAGE_KEY);
      else window.localStorage.setItem(STORAGE_KEY, value);
    } catch (_) {}
  }
  var THEME_COLOR = ${JSON.stringify({ light: themeTokens['surface.100'].light, dark: themeTokens['surface.100'].dark })};
  // Browser chrome follows the resolved theme: an explicit choice pins every
  // theme-color meta to that theme; System restores the media-query fallbacks.
  function syncThemeColor(value, resolved) {
    var metas = document.querySelectorAll('meta[name="theme-color"]');
    for (var i = 0; i < metas.length; i += 1) {
      var meta = metas[i];
      if (!meta.hasAttribute("data-media")) {
        meta.setAttribute("data-media", meta.getAttribute("media") || "");
        meta.setAttribute("data-content", meta.getAttribute("content") || "");
      }
      if (value === "system") {
        meta.setAttribute("media", meta.getAttribute("data-media"));
        meta.setAttribute("content", meta.getAttribute("data-content"));
      } else {
        meta.removeAttribute("media");
        meta.setAttribute("content", THEME_COLOR[resolved]);
      }
    }
  }
  function applyPreference(value) {
    var resolved = value === "system" ? systemTheme() : value;
    var root = document.documentElement;
    root.setAttribute(PREFERENCE_ATTR, value);
    root.setAttribute(RESOLVED_ATTR, resolved);
    if (value === "system") root.removeAttribute(OVERRIDE_ATTR);
    else root.setAttribute(OVERRIDE_ATTR, value);
    syncThemeColor(value, resolved);
    return resolved;
  }
  function syncControls() {
    var radios = document.querySelectorAll('input[name="' + CONTROL_NAME + '"]');
    for (var i = 0; i < radios.length; i += 1) radios[i].checked = radios[i].value === currentPreference;
  }
  var currentPreference = readPreference();
  applyPreference(currentPreference);
  document.addEventListener("DOMContentLoaded", function () {
    syncControls();
    var radios = document.querySelectorAll('input[name="' + CONTROL_NAME + '"]');
    for (var i = 0; i < radios.length; i += 1) {
      radios[i].addEventListener("change", function (event) {
        currentPreference = event.target.value;
        persistPreference(currentPreference);
        applyPreference(currentPreference);
      });
    }
    var btn = document.getElementById("theme-switch");
    if (btn) {
      var specimenOn = btn.getAttribute("aria-checked") === "true";
      var renderSwitch = function () {
        btn.className = specimenOn ? SWITCH_ON : SWITCH_OFF;
        btn.setAttribute("aria-checked", String(specimenOn));
      };
      renderSwitch();
      btn.addEventListener("click", function () {
        specimenOn = !specimenOn;
        renderSwitch();
      });
    }
  });
  // A page restored from the back/forward cache keeps its old DOM state:
  // re-read the stored choice in case it changed on another page meanwhile.
  window.addEventListener("pageshow", function (event) {
    if (!event.persisted) return;
    currentPreference = readPreference();
    applyPreference(currentPreference);
    syncControls();
  });
  if (media) {
    var onSystemChange = function () {
      if (currentPreference === "system") applyPreference("system");
    };
    if (typeof media.addEventListener === "function") media.addEventListener("change", onSystemChange);
    else if (typeof media.addListener === "function") media.addListener(onSystemChange);
  }
})();
`

const motionPreviewJs = `(function () {
  var btn = document.getElementById("motion-preview");
  if (!btn) return;
  var status = document.getElementById("motion-preview-status");
  var spinnerEl = document.getElementById("demo-spinner");
  var skeletonWideEl = document.getElementById("demo-skeleton-wide");
  var skeletonNarrowEl = document.getElementById("demo-skeleton-narrow");
  var media = window.matchMedia ? window.matchMedia("(prefers-reduced-motion: reduce)") : null;
  var timer = 0;
  function setStatus(text) {
    if (status) status.textContent = text;
  }
  function setStatic() {
    if (spinnerEl) spinnerEl.className = ${JSON.stringify(spinnerCss)};
    if (skeletonWideEl) skeletonWideEl.className = ${JSON.stringify(skeletonWideCss)};
    if (skeletonNarrowEl) skeletonNarrowEl.className = ${JSON.stringify(skeletonNarrowCss)};
  }
  function restartAnimation(el, className) {
    if (!el) return;
    el.className = className.static;
    void el.offsetWidth;
    el.className = className.preview;
  }
  function syncReducedMotionStatus() {
    window.clearTimeout(timer);
    setStatic();
    if (media && media.matches) {
      setStatus("Reduced motion is enabled, so the loading preview stays still.");
      return true;
    }
    setStatus("Static by default. Preview runs once, then stops automatically.");
    return false;
  }
  btn.addEventListener("click", function () {
    if (syncReducedMotionStatus()) return;
    restartAnimation(spinnerEl, { static: ${JSON.stringify(spinnerCss)}, preview: ${JSON.stringify(spinnerPreviewCss)} });
    restartAnimation(skeletonWideEl, { static: ${JSON.stringify(skeletonWideCss)}, preview: ${JSON.stringify(skeletonWidePreviewCss)} });
    restartAnimation(skeletonNarrowEl, { static: ${JSON.stringify(skeletonNarrowCss)}, preview: ${JSON.stringify(skeletonNarrowPreviewCss)} });
    setStatus("Preview running for about four seconds. It stops automatically.");
    timer = window.setTimeout(function () {
      setStatic();
      setStatus("Preview finished. Loading demos are static again.");
    }, 4200);
  });
  if (media) {
    if (media.addEventListener) {
      media.addEventListener("change", syncReducedMotionStatus);
    } else if (media.addListener) {
      media.addListener(syncReducedMotionStatus);
    }
  }
  syncReducedMotionStatus();
})();
`

const swRegisterJs = `if ('serviceWorker' in navigator) {
  window.addEventListener('load', function () {
    var prompt = document.getElementById('sw-update');
    var apply = document.getElementById('sw-update-apply');
    var dismiss = document.getElementById('sw-update-dismiss');
    var waitingWorker = null;
    var shouldRefresh = false;
    var refreshing = false;
    function showUpdate(worker) {
      waitingWorker = worker;
      if (prompt) prompt.hidden = false;
    }
    function hideUpdate() {
      if (prompt) prompt.hidden = true;
    }
    if (dismiss) dismiss.addEventListener('click', hideUpdate);
    if (apply) {
      apply.addEventListener('click', function () {
        if (!waitingWorker) return;
        shouldRefresh = true;
        hideUpdate();
        waitingWorker.postMessage({ type: 'SKIP_WAITING' });
      });
    }
    navigator.serviceWorker.addEventListener('controllerchange', function () {
      waitingWorker = null;
      hideUpdate();
      if (!shouldRefresh || refreshing) return;
      refreshing = true;
      window.location.reload();
    });
    navigator.serviceWorker.register('/sw.js').then(function (registration) {
      function watch(worker) {
        if (!worker) return;
        worker.addEventListener('statechange', function () {
          if (worker.state === 'installed' && navigator.serviceWorker.controller) showUpdate(worker);
        });
      }
      if (registration.waiting) showUpdate(registration.waiting);
      if (registration.installing) watch(registration.installing);
      registration.addEventListener('updatefound', function () {
        watch(registration.installing);
      });
    }).catch(function () {});
  });
}
`

// The service worker is written as a template: scripts/fingerprint.mjs fills
// in __VERSION__ (a hash of every shipped file, so each deploy changes sw.js
// and the browser installs the new worker) and __SHELL__ (the hashed URLs).
const swJs = `// Verdant — offline shell.
// Pages: network first, so HTML is always the deployed version when online;
// the cached copy is only a fallback. Assets: hashed filenames, so a cached
// copy can never be stale — cache first is safe.
var CACHE_PREFIX = 'verdant-';
var CACHE = CACHE_PREFIX + '__VERSION__';
var LEGACY_CACHE = /^verdant-v\\d+$/;
var SHELL = __SHELL__;
self.addEventListener('message', function (event) {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});
function normalizePage(pathname) {
  if (pathname === '/' || pathname === '/index.html') return '/';
  pathname = pathname.replace(/\\/+$/, '');
  if (pathname === '${COMPONENTS_ROUTE}' || pathname === '${COMPONENTS_FILE}') return '${COMPONENTS_ROUTE}';
  if (pathname === '/404' || pathname === '/404.html') return '/404.html';
  if (pathname === '/offline' || pathname === '/offline.html') return '/offline.html';
  return null;
}
self.addEventListener('install', function (event) {
  // cache: 'reload' skips the HTTP cache, so the new shell is never
  // assembled from an older deploy's files.
  event.waitUntil(caches.open(CACHE).then(function (cache) {
    return cache.addAll(SHELL.map(function (u) { return new Request(u, { cache: 'reload' }); }));
  }).then(function () { return caches.keys(); }).then(function (keys) {
    // The first cache-first worker (caches verdant-v1/v2) serves stale pages
    // that have no update prompt, so nothing would ever send SKIP_WAITING.
    // Replace it straight away; every newer worker waits for the prompt.
    if (keys.some(function (k) { return LEGACY_CACHE.test(k); })) return self.skipWaiting();
  }));
});
self.addEventListener('activate', function (event) {
  event.waitUntil(caches.keys().then(function (keys) {
    var old = keys.filter(function (k) { return k.indexOf(CACHE_PREFIX) === 0 && k !== CACHE; });
    return Promise.all(old.map(function (k) { return caches.delete(k); }))
      .then(function () { return self.clients.claim(); });
  }));
});
self.addEventListener('fetch', function (event) {
  var req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    var page = normalizePage(new URL(req.url).pathname);
    event.respondWith(fetch(req).then(function (res) {
      if (res.ok && page) { var copy = res.clone(); caches.open(CACHE).then(function (c) { c.put(page, copy); }); }
      return res;
    }).catch(function () {
      return caches.open(CACHE).then(function (cache) {
        if (page) {
          return cache.match(page).then(function (hit) {
            return hit || cache.match('/offline.html');
          });
        }
        return cache.match('/offline.html');
      });
    }));
    return;
  }
  event.respondWith(caches.match(req).then(function (hit) { return hit || fetch(req); }));
});
`

// Light, safe HTML minification: collapse inter-tag whitespace only — never
// touches text content (and <pre> blocks are left alone), so copy stays intact.
const minifyHtml = (html) => {
  const pres = []
  const held = html.replace(/<pre[\s\S]*?<\/pre>/gu, (m) => `<!--pre:${pres.push(m) - 1}-->`)
  const collapsed = held.replace(/>\s+</gu, '><').replace(/<!--pre:(\d+)-->/gu, (_, i) => pres[Number(i)])
  return `${collapsed.trim()}\n`
}

// ---- write ---------------------------------------------------------------------

mkdirSync('dist', { recursive: true })
writeFileSync('dist/theme-toggle.js', themeToggleJs)
// The gallery's motion preview needs the DOM, so it ships separately and deferred.
writeFileSync('dist/gallery.js', motionPreviewJs)
writeFileSync('dist/sw-register.js', swRegisterJs)
writeFileSync('dist/sw.js', swJs)
copyDir('public', 'dist')

writeFileSync('dist/index.html', minifyHtml(page({
  title: 'Verdant — Sustainable Defaults for the Green Web',
  description: 'Verdant is a lightweight design-system starter with defaults aligned to selected Web Sustainability Guidelines. Built with PandaCSS.',
  path: '/',
  active: 'home',
  jsonLd: {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'Verdant',
    description: 'A lightweight design-system starter with defaults aligned to selected Web Sustainability Guidelines.',
    url: 'https://verdant-wsg-demo.netlify.app/',
  },
  bodyHtml: heroHtml + statsHtml + stagesHtml + paletteHtml + tokensHtml + scoreHtml + pandaHtml + ctaHtml,
})))

writeFileSync('dist/components.html', minifyHtml(page({
  title: 'Components — Verdant',
  description: 'Documented component specimens for the Verdant design system: links, buttons, fields, switches, status cards, and loading patterns.',
  path: COMPONENTS_ROUTE,
  active: 'components',
  bodyHtml: componentsBody,
  scripts: ['/gallery.js'],
})))

writeFileSync('dist/404.html', minifyHtml(page({
  title: 'Page not found — Verdant',
  description: 'The page you were looking for does not exist.',
  path: '/404.html',
  active: '',
  bodyHtml: notFoundBody,
})))

writeFileSync('dist/offline.html', minifyHtml(page({
  title: 'Offline — Verdant',
  description: 'You are offline and this page is not available yet.',
  path: '/offline.html',
  active: '',
  bodyHtml: offlineBody,
})))

console.log('Wrote dist/index.html, dist/components.html, dist/404.html, dist/offline.html')
