// Verdant demo site — generated by Panda. This script is the only "source"
// Panda extracts from (see panda.config.ts `include`): every css()/pattern()/
// recipe() call below is a literal call, so `panda cssgen` can statically
// find it and emit exactly the CSS the pages use, nothing more.
import { writeFileSync, mkdirSync, readFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'

// A hand-rolled recursive copy: some mounted/virtual filesystems choke on
// Node's native cpSync fast paths (fcopyfile/clonefile), so this sticks to
// plain read/write, which works everywhere.
function copyDir(src, dest) {
  mkdirSync(dest, { recursive: true })
  for (const entry of readdirSync(src)) {
    const srcPath = join(src, entry)
    const destPath = join(dest, entry)
    if (statSync(srcPath).isDirectory()) {
      copyDir(srcPath, destPath)
    } else {
      writeFileSync(destPath, readFileSync(srcPath))
    }
  }
}
import { css } from '../styled-system/css/index.mjs'
import { flex, vstack, hstack, container } from '../styled-system/patterns/index.mjs'
import { button, card, fieldInput, switchTrack, spinner, skeleton } from '../styled-system/recipes/index.mjs'

const DECOR_ICON =
  'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20viewBox%3D%220%200%2064%2064%22%20width%3D%2264%22%20height%3D%2264%22%3E%3Crect%20width%3D%2264%22%20height%3D%2264%22%20rx%3D%2212%22%20fill%3D%22%232f6b4a%22/%3E%3Ccircle%20cx%3D%2220%22%20cy%3D%2220%22%20r%3D%223%22%20fill%3D%22%23faf8f3%22/%3E%3Ccircle%20cx%3D%2236%22%20cy%3D%2220%22%20r%3D%223%22%20fill%3D%22%23faf8f3%22/%3E%3Ccircle%20cx%3D%2220%22%20cy%3D%2236%22%20r%3D%223%22%20fill%3D%22%23faf8f3%22/%3E%3Ccircle%20cx%3D%2236%22%20cy%3D%2236%22%20r%3D%223%22%20fill%3D%22%23faf8f3%22/%3E%3Ccircle%20cx%3D%2244%22%20cy%3D%2244%22%20r%3D%223%22%20fill%3D%22%23faf8f3%22/%3E%3C/svg%3E'

// ---- shared, literal style calls (what panda extracts) --------------------

const skipLinkCss = css({
  position: 'absolute', left: '3', top: '-48px',
  background: 'surface.200', color: 'ink', paddingBlock: '2', paddingInline: '4',
  borderRadius: 'sm', border: '1px solid', borderColor: 'border', zIndex: '10',
  _motionSafe: { transition: 'top 120ms ease' },
  _focus: { top: '3' },
})

const headerCss = css({ borderBottom: '1px solid', borderColor: 'border' })
const barCss = flex({
  maxWidth: '880px', marginX: 'auto', paddingBlock: '4', paddingInline: '6',
  align: 'center', justify: 'space-between', gap: '4', wrap: 'wrap',
})
const wordmarkCss = css({ fontSize: 'displaySm', lineHeight: 'displaySm', fontWeight: '700', margin: '0' })
const wordmarkLinkCss = css({ color: 'ink', textDecoration: 'none' })
const navListCss = hstack({ gap: '4', listStyle: 'none', margin: '0', padding: '0' })
const navLinkCss = css({ textDecoration: 'none', fontSize: 'bodySm', fontWeight: '600', color: 'ink' })
const navLinkActiveCss = css({ textDecoration: 'none', fontSize: 'bodySm', fontWeight: '600', color: 'accent' })

const breadcrumbNavCss = css({ maxWidth: '880px', marginX: 'auto', paddingInline: '6', paddingTop: '3', fontSize: 'label', color: 'ink.muted' })
const breadcrumbListCss = hstack({ gap: '1', listStyle: 'none', margin: '0', padding: '0' })
const breadcrumbLinkCss = css({ color: 'ink.muted' })

const mainCss = css({ maxWidth: '880px', marginX: 'auto', paddingBlock: '8', paddingInline: '6' })
const heroHeadingCss = css({ fontSize: 'displayLg', lineHeight: 'displayLg', fontWeight: '700', margin: '0 0 16px' })
const ledeCss = css({ fontSize: 'body', color: 'ink.muted', maxWidth: '60ch', margin: '0' })
const sectionCss = css({ marginTop: '12' })
const sectionHeadingCss = css({ fontSize: 'displayMd', lineHeight: 'displayMd', fontWeight: '700', margin: '0 0 16px' })

const gridCss = css({ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '4' })
const cardHeadingCss = css({ fontSize: 'displaySm', lineHeight: 'displaySm', fontWeight: '600', margin: '0 0 4px' })
const cardBodyCss = css({ color: 'ink.muted', margin: '0', fontSize: 'bodySm', lineHeight: 'bodySm' })
const statusCss = hstack({ gap: '1', fontSize: 'label', lineHeight: 'label', fontWeight: '600', marginTop: '3' })
const statusPositiveCss = css({ color: 'positive' })
const statusCriticalCss = css({ color: 'critical' })

const checklistTableCss = css({ width: '100%', borderCollapse: 'collapse', fontSize: 'bodySm' })
const checklistThCss = css({ textAlign: 'left', paddingBlock: '2', paddingInline: '3', borderBottom: '1px solid', borderColor: 'border' })
const checklistTdCss = checklistThCss

const footerCss = css({ borderTop: '1px solid', borderColor: 'border', marginTop: '12' })
const footerBarCss = flex({
  maxWidth: '880px', marginX: 'auto', paddingBlock: '4', paddingInline: '6',
  align: 'center', justify: 'space-between', gap: '4', wrap: 'wrap',
})
const footerTextCss = css({ color: 'ink.muted', fontSize: 'label' })

const decorWrapCss = css({ display: 'block' })

const rowCss = flex({ gap: '3', align: 'center', wrap: 'wrap' })
const captionCss = css({ fontSize: 'label', color: 'ink.muted' })
const codeCss = css({ fontFamily: 'mono', fontSize: 'label' })

const formCss = vstack({ gap: '3', alignItems: 'flex-start', maxWidth: '320px' })
const fieldCss = vstack({ gap: '1', alignItems: 'flex-start', width: '100%' })
const labelCss = css({ fontSize: 'label', lineHeight: 'label', fontWeight: '600' })
const hintCss = css({ fontSize: 'bodySm', color: 'ink.muted', margin: '0' })

const switchRowCss = flex({ align: 'center', gap: '3' })
const noteCss = css({ marginTop: '3', fontSize: 'label', color: 'ink.muted', maxWidth: '60ch' })

const motionRowCss = flex({ align: 'center', gap: '6', wrap: 'wrap' })
const motionGroupCss = vstack({ gap: '2', alignItems: 'flex-start' })

const btnPrimary = button({ variant: 'primary' })
const btnSecondary = button({ variant: 'secondary' })
const cardCss = card()
const inputCss = fieldInput()
const switchOffCss = switchTrack()
const spinnerCss = spinner()
const skeletonCss = skeleton()

// ---- page shell -------------------------------------------------------

const nav = (active) => `
  <header class="${headerCss}">
    <div class="${barCss}">
      <p class="${wordmarkCss}"><a class="${wordmarkLinkCss}" href="/">Verdant</a></p>
      <nav aria-label="Primary">
        <ul class="${navListCss}">
          <li><a class="${active === 'home' ? navLinkActiveCss : navLinkCss}" href="/" ${active === 'home' ? 'aria-current="page"' : ''}>Home</a></li>
          <li><a class="${active === 'components' ? navLinkActiveCss : navLinkCss}" href="/components.html" ${active === 'components' ? 'aria-current="page"' : ''}>Components</a></li>
        </ul>
      </nav>
    </div>
  </header>`

const breadcrumb = (label) => `
  <nav class="${breadcrumbNavCss}" aria-label="Breadcrumb">
    <ol class="${breadcrumbListCss}">
      <li><a class="${breadcrumbLinkCss}" href="/">Home</a></li>
      <li aria-hidden="true">/</li>
      <li>${label}</li>
    </ol>
  </nav>`

const footer = () => `
  <footer class="${footerCss}">
    <div class="${footerBarCss}">
      <p class="${footerTextCss}">Built by Ivan, styled with PandaCSS, tuned to the W3C Web Sustainability Guidelines.</p>
      <p class="${footerTextCss}"><a href="https://github.com/ivanoats/wsg-check">wsg-check</a></p>
    </div>
  </footer>`

const page = ({ title, description, active, jsonLd, bodyHtml, extraHead = '' }) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<meta name="description" content="${description}">
<link rel="canonical" href="https://verdant-wsg-demo.netlify.app/${active === 'home' ? '' : active + '.html'}">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${description}">
<meta property="og:type" content="website">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="manifest" href="/manifest.json">
<meta name="theme-color" content="#2f6b4a">
<link rel="stylesheet" href="/styles.css">
${jsonLd ? `<script type="application/ld+json">${JSON.stringify(jsonLd)}</script>` : ''}
${extraHead}
</head>
<body>
<a class="${skipLinkCss}" href="#main">Skip to content</a>
${nav(active)}
${active === 'components' ? breadcrumb('Components') : ''}
<main id="main" class="${mainCss}">
${bodyHtml}
</main>
${footer()}
<script src="/sw-register.js" defer></script>
</body>
</html>
`

// ---- index.html ---------------------------------------------------------

const checklistRows = [
  ['System-stack typography, zero font files', '2.18 Highly optimize typography', 'No font payload'],
  ['Dark theme via <code class="' + codeCss + '">prefers-color-scheme</code>', '3.12 Sustainable CSS preference queries', 'Dark-mode media query present'],
  ['Motion gated on <code class="' + codeCss + '">prefers-reduced-motion</code>', '2.17 Control animations proportionately', 'Animations guarded, not unconditional'],
  ['Borders over shadows by default', '2.15 / general payload', 'Leaner generated CSS'],
  ['Explicit image size, lazy-loading, alt text', '2.15 Optimize images', 'Modern formats, loading=lazy, alt present'],
  ['No autoplay, no urgency copy', '2.6, 2.9, 2.11', 'Non-essential / deceptive content checks'],
  ['Landmarks + labelled fields', '2.8 Navigation, UX &amp; Design forms', 'main/nav present, labels/autocomplete on fields'],
  ['One focus-ring token, always visible', '2.2 Access barriers', 'Focus indicator present and consistent'],
  ['Extracted, used-only CSS via PandaCSS', '2.13 Implement a design system', 'No redundant / unused styles shipped'],
].map(([decision, guideline, check]) => `
  <tr>
    <td class="${checklistTdCss}">${decision}</td>
    <td class="${checklistTdCss}">${guideline}</td>
    <td class="${checklistTdCss}">${check}</td>
  </tr>`).join('')

const indexBody = `
<div>
  <h1 class="${heroHeadingCss}">Verdant</h1>
  <p class="${ledeCss}">A small, from-scratch design system where every default is chosen to satisfy the W3C Web Sustainability Guidelines (WSG) &mdash; not just the spirit of them, the specific checks a scanner like <a href="https://github.com/ivanoats/wsg-check">wsg-check</a> runs. This page and its <a href="/components.html">component gallery</a> are the system, deployed, so the checks run against something real.</p>
</div>

<section class="${sectionCss}">
  <h2 class="${sectionHeadingCss}">What ships zero-cost</h2>
  <div class="${gridCss}">
    <div class="${cardCss}">
      <h3 class="${cardHeadingCss}">No web fonts</h3>
      <p class="${cardBodyCss}">Type is a system-ui stack. The fastest font is the one nobody downloads.</p>
    </div>
    <div class="${cardCss}">
      <h3 class="${cardHeadingCss}">Native dark mode</h3>
      <p class="${cardBodyCss}">One token set, two values, switched by <code class="${codeCss}">prefers-color-scheme</code> &mdash; no second stylesheet.</p>
    </div>
    <div class="${cardCss}">
      <h3 class="${cardHeadingCss}">Motion opt-in only</h3>
      <p class="${cardBodyCss}">Every animation lives inside <code class="${codeCss}">prefers-reduced-motion: no-preference</code>.</p>
    </div>
  </div>
</section>

<section class="${sectionCss}">
  <h2 class="${sectionHeadingCss}">Sustainability checklist</h2>
  <table class="${checklistTableCss}">
    <thead>
      <tr>
        <th class="${checklistThCss}" scope="col">Decision</th>
        <th class="${checklistThCss}" scope="col">WSG guideline</th>
        <th class="${checklistThCss}" scope="col">What a scanner checks</th>
      </tr>
    </thead>
    <tbody>${checklistRows}</tbody>
  </table>
</section>

<section class="${sectionCss}">
  <h2 class="${sectionHeadingCss}">See it live</h2>
  <p class="${ledeCss}">Buttons, cards, a labelled form field, a real dark-mode switch, and a reduced-motion-aware spinner &mdash; each built to the pattern described above.</p>
  <a class="${btnPrimary}" href="/components.html">View components</a>
</section>
`

// ---- components.html ------------------------------------------------------

const componentsBody = `
<div>
  <h1 class="${heroHeadingCss}">Components</h1>
  <p class="${ledeCss}">Five patterns, each demonstrating one WSG-relevant behavior live rather than just describing it.</p>
</div>

<section class="${sectionCss}">
  <h2 class="${sectionHeadingCss}">Buttons</h2>
  <p class="${captionCss}">Default &mdash; hover is real, try it</p>
  <div class="${rowCss}">
    <button class="${btnPrimary}">Save changes</button>
    <button class="${btnSecondary}">Cancel</button>
    <button class="${btnPrimary}" disabled>Save changes</button>
  </div>
</section>

<section class="${sectionCss}">
  <h2 class="${sectionHeadingCss}">Cards</h2>
  <div class="${gridCss}">
    <div class="${cardCss}">
      <h3 class="${cardHeadingCss}">Homepage scan</h3>
      <p class="${cardBodyCss}">18 checks passed, 2 warnings, 0 failures.</p>
      <div class="${statusCss} ${statusPositiveCss}">&#10003; Passing</div>
    </div>
    <div class="${cardCss}">
      <h3 class="${cardHeadingCss}">Checkout flow</h3>
      <p class="${cardBodyCss}">Render-blocking script found on the payment step.</p>
      <div class="${statusCss} ${statusCriticalCss}">&#9888; Needs attention</div>
    </div>
  </div>
</section>

<section class="${sectionCss}">
  <h2 class="${sectionHeadingCss}">Form field</h2>
  <form class="${formCss}">
    <div class="${fieldCss}">
      <label class="${labelCss}" for="site-url">Website URL</label>
      <input class="${inputCss}" id="site-url" name="url" type="url" inputmode="url" autocomplete="url" placeholder="https://example.com">
      <p class="${hintCss}">One field &mdash; enough to run a scan, nothing else required.</p>
    </div>
  </form>
</section>

<section class="${sectionCss}">
  <h2 class="${sectionHeadingCss}">Theme toggle</h2>
  <div class="${switchRowCss}">
    <button type="button" class="${switchOffCss}" role="switch" aria-checked="false" id="theme-switch">
      <span class="knob"></span>
    </button>
    <label class="${labelCss}" for="theme-switch">Dark theme</label>
  </div>
  <p class="${noteCss}">This page already switches with your OS. The toggle overrides that by setting the same tokens as an inline style on the root &mdash; it never fights the stylesheet for priority.</p>
</section>

<section class="${sectionCss}">
  <h2 class="${sectionHeadingCss}">Motion</h2>
  <div class="${motionRowCss}">
    <div class="${motionGroupCss}">
      <div class="${spinnerCss}" role="status" aria-label="Scanning"></div>
      <span class="${captionCss}">Spinner</span>
    </div>
    <div class="${motionGroupCss}">
      <div class="${skeletonCss}" style="width:160px;height:14px;"></div>
      <div class="${skeletonCss}" style="width:110px;height:14px;"></div>
      <span class="${captionCss}">Skeleton</span>
    </div>
  </div>
</section>

<section class="${sectionCss}">
  <h2 class="${sectionHeadingCss}">A decorative mark</h2>
  <p class="${ledeCss}">Purely decorative, so it carries <code class="${codeCss}">alt=""</code>, real dimensions, and drops out entirely for anyone who's asked to save data.</p>
  <img class="${decorWrapCss} decor" src="${DECOR_ICON}" width="64" height="64" alt="" loading="lazy">
</section>
`

const themeToggleJs = `(function () {
  var LIGHT = { "surface.100": "#faf8f3", "surface.200": "#ffffff", "border": "#93866c", "ink": "#1c1a15", "ink.muted": "#5b5548", "accent": "#2f6b4a", "accent.strong": "#234f38", "accent.ink": "#ffffff", "focusRing": "#a5670a", "positive": "#1f7a6c", "critical": "#c1440e" };
  var DARK = { "surface.100": "#15140f", "surface.200": "#1e1c15", "border": "#726b53", "ink": "#f1ede2", "ink.muted": "#b6ae9c", "accent": "#7fcfa3", "accent.strong": "#5fb98c", "accent.ink": "#10241a", "focusRing": "#e8a83e", "positive": "#5cc9b7", "critical": "#ff8f5e" };
  function varName(key) { return "--colors-" + key.replace(/\\./g, "-"); }
  function apply(map) {
    var root = document.documentElement;
    Object.keys(map).forEach(function (k) { root.style.setProperty(varName(k), map[k]); });
  }
  var btn = document.getElementById("theme-switch");
  if (!btn) return;
  // Reflect the OS-driven theme that's already on screen, so the switch
  // never lies about the current state before it's touched.
  var forcedDark = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
  btn.setAttribute("aria-checked", String(forcedDark));
  btn.addEventListener("click", function () {
    forcedDark = !forcedDark;
    btn.setAttribute("aria-checked", String(forcedDark));
    apply(forcedDark ? DARK : LIGHT);
  });
})();
`

const swRegisterJs = `if ('serviceWorker' in navigator) {
  window.addEventListener('load', function () {
    navigator.serviceWorker.register('/sw.js');
  });
}
`

const swJs = `// Verdant — minimal offline shell. Cache the three pages and their assets
// on install; serve cache-first, fall back to network, fall back to the
// cached page for navigations when both fail.
var CACHE = 'verdant-v1';
var SHELL = ['/', '/index.html', '/components.html', '/404.html', '/styles.css', '/theme-toggle.js', '/favicon.svg', '/manifest.json'];
self.addEventListener('install', function (event) {
  event.waitUntil(caches.open(CACHE).then(function (cache) { return cache.addAll(SHELL); }));
  self.skipWaiting();
});
self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) { return k !== CACHE; }).map(function (k) { return caches.delete(k); }));
    })
  );
  self.clients.claim();
});
self.addEventListener('fetch', function (event) {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then(function (cached) {
      return cached || fetch(event.request).catch(function () {
        if (event.request.mode === 'navigate') return caches.match('/index.html');
      });
    })
  );
});
`

// Light, safe HTML minification: collapse inter-tag whitespace only — never
// touches text content, so copy stays intact.
const minifyHtml = (html) => html.replace(/>\s+</g, '><').trim() + '\n'

mkdirSync('dist', { recursive: true })
writeFileSync('dist/theme-toggle.js', themeToggleJs)
writeFileSync('dist/sw-register.js', swRegisterJs)
writeFileSync('dist/sw.js', swJs)
copyDir('public', 'dist')

writeFileSync('dist/index.html', minifyHtml(page({
  title: 'Verdant — a sustainability-first design system',
  description: 'A small, from-scratch design system built to satisfy the W3C Web Sustainability Guidelines, styled with PandaCSS.',
  active: 'home',
  jsonLd: {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'Verdant',
    description: 'A small, from-scratch design system built to satisfy the W3C Web Sustainability Guidelines.',
    url: 'https://verdant-wsg-demo.netlify.app/',
  },
  bodyHtml: indexBody,
})))

writeFileSync('dist/components.html', minifyHtml(page({
  title: 'Components — Verdant',
  description: 'Live component gallery for the Verdant design system: buttons, cards, form fields, theme toggle, and motion patterns.',
  active: 'components',
  bodyHtml: componentsBody,
  extraHead: '',
}).replace('</body>', '<script src="/theme-toggle.js" defer></script>\n</body>')))

writeFileSync('dist/404.html', minifyHtml(page({
  title: 'Page not found — Verdant',
  description: 'The page you were looking for does not exist.',
  active: 'home',
  bodyHtml: `
    <h1 class="${heroHeadingCss}">Page not found</h1>
    <p class="${ledeCss}">That page doesn't exist. <a href="/">Back to the overview</a>.</p>
  `,
})))

console.log('Wrote dist/index.html, dist/components.html, dist/404.html')
